"""Emit every material parameter in a form that can be checked line by line against a source.

Written because the InAs/InSb parameter set failed its first benchmark (Pryor & Pistol 2005) and
the failure localized to the hydrostatic deformation potentials -- see
`scripts/insb_pryor_pistol_check.py` and the README. The point of this script is to put the whole
set, including the derived quantities and the sign conventions, in one auditable place rather
than have someone re-transcribe it by hand.

Everything here is READ FROM `materials.py`, not retyped, so the document cannot drift from the
code. Run:  python scripts/dump_sb_parameters.py > SB_PARAMETERS.md
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import numpy as np

import materials as mt
import materials_sb as ms
import pryor1998 as pr
import elasticity_fd as ef

MATS = mt.BINARIES                 # ('GaAs', 'InAs', 'GaSb', 'InSb')
COLS = '| ' + ' | '.join(MATS) + ' |'
RULE = '|---' * (len(MATS) + 1) + '|'

#: The three the legacy aestimo comparison covers. GaAs was never in that part of the story --
#: it arrived with the workbook -- so the "database vs review" tables below stay three wide.
MATS3 = ('InAs', 'GaSb', 'InSb')
COLS3 = '| ' + ' | '.join(MATS3) + ' |'
RULE3 = '|---' * (len(MATS3) + 1) + '|'
P = print


def row(name, fmt='{:.4f}', note=''):
    P(f"| `{name}` |" + '|'.join(f" {fmt.format(mt.MATERIALS[m][name])} " for m in MATS)
      + f"| {mt.PROVENANCE.get(name, '')} | {note} |")


if __name__ == '__main__':
    M = mt.MATERIALS
    P("# III-V parameter set — full audit sheet")
    P("")
    P("Generated by `scripts/dump_sb_parameters.py`, reading `materials.py` directly.")
    P("Every value below is what the code actually uses. Nothing is retyped.")
    P("")
    P(f"Table evaluated at **T = {mt.TEMPERATURE:g} K**. Two quantities move with temperature:")
    P("the gaps (Varshni) and the lattice constants, and therefore every misfit and every strain.")
    P("")
    P("## Read this first: the two conventions that decide whether a number is 'wrong'")
    P("")
    P("**1. Sign convention for `a_v`.** This package applies")
    P("")
    P("```")
    P("    E_c = E_c(unstrained) + a_c * Tr(eps)")
    P("    E_v = E_v(unstrained) - a_v * Tr(eps)        <-- MINUS")
    P("```")
    P("")
    P("which is Pryor's convention, in which the hydrostatic **gap** deformation potential is")
    P("")
    P("```")
    P("    a_gap = a_c + a_v")
    P("```")
    P("")
    P("**Vurgaftman, Meyer and Ram-Mohan (2001) use this same convention**, and say so explicitly")
    P("— their `a_v` is negative for all four binaries here, and the gap potential is the SUM.")
    P("Since every number below is transcribed from their tables, no conversion is applied")
    P("anywhere and none is needed.")
    P("")
    P("The commoner tabulation (Van de Walle) has `E_v` shifting by `+a_v*Tr(eps)`, quotes `a_v`")
    P("positive, and forms `a_gap = a_c - a_v`. **The two differ by 2\\*a_v.** If you check `a_v`")
    P("against a source in that convention, convert first: `a_v(ours) = -a_v(theirs)`.")
    P("`qdsolver_core.MATERIALS` is in that other convention and is deliberately not migrated,")
    P("because the validated Pryor InAs/GaAs reproductions read it; do not mix the two.")
    P("")
    P("The quantity that is convention-independent, and therefore the one to check, is `a_gap`.")
    P("It is given for every material below.")
    P("")
    P("**2. Units.** Energies eV, elastic constants GPa, lattice constants Angstrom, `e14` C/m^2.")
    P("The workbook's elastic-constant rows are labelled GPa but tabulated in 10^9 dyne/cm^2")
    P("(GaAs `c11 = 1221` is 122.1 GPa); they are stored here in GPa. This supersedes an earlier")
    P("source, aestimo's `database.py`, which stored InAs `C11 = 8.329` (10^11 dyne/cm^2) beside")
    P("InSb `68.47` (GPa) — two units in one table, which made aestimo read GaSb and InSb 10x too")
    P("stiff. Nothing here imports that file.")
    P("")
    P("---")
    P("")
    P("## Switches currently in force")
    P("")
    P("| switch | value | effect |")
    P("|---|---|---|")
    P(f"| `materials.TEMPERATURE` | {mt.TEMPERATURE:g} K | sets the gaps *and* the lattice "
      "constants |")
    P(f"| `GAP_SOURCE` | `{ms.GAP_SOURCE}` | legacy; which band gaps, see the temperature "
      "section |")
    P(f"| `GASB_AV_CONVENTION` | `{ms.GASB_AV_CONVENTION}` | legacy, deprecated; GaSb `a_v` = "
      f"{M['GaSb']['a_v']:+.2f} eV |")
    P(f"| `GASB_VBO_SOURCE` | `{ms.GASB_VBO_SOURCE}` | legacy; GaSb `VBO` = "
      f"{M['GaSb']['VBO']:+.2f} eV |")
    P(f"| `INGASB_EG_BOWING` | {ms.INGASB_EG_BOWING} eV | In(x)Ga(1-x)Sb gap bowing |")
    P(f"| `INGASB_VBO_BOWING` | {ms.INGASB_VBO_BOWING} eV | 0 = linear VBO interpolation |")
    P("")
    P("The three tagged *legacy* live in `materials_sb` and exist only to reproduce pre-audit")
    P("behaviour on demand. Each is now known to be a worse choice than the default.")
    P("")
    P("---")
    P("")
    P("## The binaries")
    P("")
    P("| parameter " + COLS + " provenance | notes |")
    P(RULE + "---|---|")
    for k, fmt, note in (
            ('Eg', '{:.4f}', 'band gap; temperature-dependent, see below'),
            ('delta_so', '{:.4f}', 'spin-orbit splitting'),
            ('Ep', '{:.4f}', 'Kane matrix element'),
            ('F', '{:.4f}', 'Kane remote-band parameter; DERIVES m_e'),
            ('gamma1L', '{:.4f}', 'Luttinger'),
            ('gamma2L', '{:.4f}', 'Luttinger'),
            ('gamma3L', '{:.4f}', 'Luttinger'),
            ('a_c', '{:.4f}', '**conduction hydrostatic deformation potential**'),
            ('a_v', '{:.4f}', '**valence hydrostatic; SIGN CONVENTION — see above**'),
            ('b', '{:.4f}', 'biaxial shear deformation potential'),
            ('d', '{:.4f}', '[111] shear deformation potential'),
            ('e14', '{:.4f}', 'piezoelectric constant'),
            ('eps_R', '{:.4f}', 'static dielectric constant'),
            ('C11', '{:.3f}', 'elastic constant, GPa'),
            ('C12', '{:.3f}', 'elastic constant, GPa'),
            ('C44', '{:.3f}', 'elastic constant, GPa'),
            ('a0', '{:.4f}', 'lattice constant, Angstrom; **temperature-dependent**'),
            ('VBO', '{:.4f}', "valence edge on the review's scale (InSb = 0); only "
                              'differences are physical'),
            ('m_e', '{:.4f}', 'tabulated; `electron_mass()` derives it instead — see below'),
            ('Eg_X', '{:.4f}', 'X-valley gap; carried, not strain-shifted'),
            ('Eg_L', '{:.4f}', 'L-valley gap; carried, not strain-shifted'),
    ):
        row(k, fmt, note)
    P("")
    P("### Derived, and convention-independent — check these")
    P("")
    P("| quantity " + COLS + " definition |")
    P(RULE + "---|")
    P("| **`a_gap = a_c + a_v`** |" + '|'.join(
        f" **{mt.a_gap(M[m]):+.2f}** " for m in MATS) +
      "| hydrostatic gap deformation potential |")
    P("| `VBO` rel. InAs |" + '|'.join(
        f" {M[m]['VBO']-M['InAs']['VBO']:+.3f} " for m in MATS) + "| unstrained valence offset |")
    P("| misfit on InAs (%) |" + '|'.join(
        f" {mt.misfit(M[m], M['InAs'])*100:+.3f} " for m in MATS) +
      "| (a_InAs - a_layer)/a_layer |")
    P("| `m_e` derived (m0) |" + '|'.join(
        f" {mt.electron_mass(M[m]):.5f} " for m in MATS) + "| Kane, from Eg/delta/Ep/F |")
    Kmu = {m: ef.voigt_moduli(M[m]['C11'], M[m]['C12'], M[m]['C44']) for m in MATS}
    P("| bulk modulus K (GPa) |" + '|'.join(f" {Kmu[m][0]:.2f} " for m in MATS) + "| Voigt average |")
    P("| shear modulus mu (GPa) |" + '|'.join(f" {Kmu[m][1]:.2f} " for m in MATS) + "| Voigt average |")
    P("| m_hh [001] |" + '|'.join(
        f" {1/(M[m]['gamma1L']-2*M[m]['gamma2L']):.4f} " for m in MATS) + "| 1/(g1 - 2 g2) |")
    P("| m_lh [001] |" + '|'.join(
        f" {1/(M[m]['gamma1L']+2*M[m]['gamma2L']):.4f} " for m in MATS) + "| 1/(g1 + 2 g2) |")
    P("")
    P("The derived `m_e` row reproduces the tabulated `m_e` row above **to the digit for all")
    P("four binaries**. That is a joint constraint on `Eg`, `delta_so`, `Ep` and `F`")
    P("simultaneously, and it is the sharpest single check that the set is internally consistent")
    P("— and that it is a 0 K set. See the temperature section.")
    P("")
    P("---")
    P("")
    P("## The alloys")
    P("")
    P("Two, both parameterised by `x` = the InSb fraction. Interpolation is")
    P("`P(x) = x*P_A + (1-x)*P_B - C*x*(1-x)`, with `C` from")
    P("`bowingparameters_vurgaftman_2001.xlsx` and `C = 0` — linear — for every key not listed")
    P("there. That includes the Luttinger parameters, the deformation potentials, the elastic")
    P("constants, `VBO`, and the lattice constant (Vegard's law).")
    P("")
    P("| alloy | endpoints | bowed keys |")
    P("|---|---|---|")
    for name in mt.ALLOYS:
        spec = mt._BOWING[name]
        bows = ', '.join(f"`{k}` {v}" for k, v in spec['bowing'].items())
        P(f"| `{name}` | x=0 → {spec['parents'][1]}, x=1 → {spec['parents'][0]} | {bows} |")
    P("")
    P("`InAsSb`'s two large bowings are not typos. `Eg` bowing of 0.67 eV drives the gap to a")
    P("minimum **below either parent** at midcomposition, which is why that alloy is used for")
    P("long-wavelength infrared; `delta_so` bowing of 1.2 eV pulls the split-off from a 0.6 eV")
    P("linear value down to 0.30 eV there.")
    P("")
    P("| alloy | Eg | delta_so | m_e tabulated | m_e derived | ratio |")
    P("|---|---|---|---|---|---|")
    for name in mt.ALLOYS:
        for x in (0.25, 0.5, 0.75):
            a = mt.alloy(name, x)
            der = mt.electron_mass(a)
            P(f"| {a['name']} | {a['Eg']:.4f} | {a['delta_so']:.4f} | {a['m_e']:.4f} | "
              f"{der:.4f} | {der/a['m_e']:.3f} |")
    P("")
    P("**The alloy electron mass is not well determined.** Bowing `m_e` directly and bowing the")
    P("ingredients of the Kane expression are two different prescriptions, and the review's")
    P("recommended values are not consistent between them: the strong `Eg` bowing pulls the")
    P("derived mass down faster than the tabulated `m_e` bowing does, by 9–16% depending on")
    P("composition. `electron_mass()` stays authoritative because the eight-band Hamiltonian is")
    P("assembled from `Ep`, `F`, `Eg` and `delta_so` and has no other option. Read the spread as")
    P("the real uncertainty — and note it lands squarely on the confinement threshold, which")
    P("goes as `1/m`.")
    P("")
    P("---")
    P("")
    P("## Temperature: the gaps, the lattice, and a check that picks a winner")
    P("")
    P("Two things move with `T`, and `materials.set_temperature(T)` moves both:")
    P("")
    P("```")
    P("    Eg(T) = Eg(0) - alpha*T^2 / (T + beta)         Varshni")
    P("    a0(T) = a0(300 K) + da/dT * (T - 300)          linear")
    P("```")
    P("")
    P("The lattice constant is the one that is easy to forget and hard to notice. It is the")
    P("**only** thing that sets the misfit, and the misfit drives every strain result:")
    P("")
    P("| | 0 K | 77 K | 300 K |")
    P("|---|---|---|---|")
    _rows = {}
    for _T in (0.0, 77.0, 300.0):
        mt.set_temperature(_T)
        _rows[_T] = (mt.misfit(M['InSb'], M['InAs']) * 100, M['InAs']['Eg'], M['InSb']['Eg'],
                     mt.electron_mass(M['InSb']))
    mt.set_temperature(0.0)
    P("| InSb-on-InAs misfit (%) |" + '|'.join(f" {_rows[t][0]:+.4f} " for t in (0., 77., 300.))
      + "|")
    P("| `Eg` InAs (eV) |" + '|'.join(f" {_rows[t][1]:.4f} " for t in (0., 77., 300.)) + "|")
    P("| `Eg` InSb (eV) |" + '|'.join(f" {_rows[t][2]:.4f} " for t in (0., 77., 300.)) + "|")
    P("| derived `m_e` InSb |" + '|'.join(f" {_rows[t][3]:.5f} " for t in (0., 77., 300.)) + "|")
    P("")
    P("The misfit moves only 0.4% of itself between 0 K and 300 K — worth about 1.5 meV on a")
    P("converged InSb dot gap — but mixing temperatures is how this project got into trouble")
    P("once already, in the other direction: the GaSb offset was derived from a 0 K table while")
    P("the gaps in force were ~300 K.")
    P("")
    P("### The legacy `database` gaps, and why they lost")
    P("")
    P(COLS3.replace('| InAs', '| | InAs'))
    P(RULE3)
    P("| `database` (~300 K, the OLD default) |" +
      '|'.join(f" {ms._DATABASE_EG[m]:.3f} " for m in MATS3) + "|")
    ms.set_gap_source('varshni', 0.0)
    eg0 = {m: M[m]['Eg'] for m in MATS3}
    me0 = {m: mt.electron_mass(M[m]) for m in MATS3}
    P("| **Varshni at T = 0 K (current default)** |" +
      '|'.join(f" **{eg0[m]:.3f}** " for m in MATS3) + "|")
    P("| Varshni `alpha` (eV/K) |" +
      '|'.join(f" {ms._VARSHNI[m]['alpha']:.3e} " for m in MATS3) + "|")
    P("| Varshni `beta` (K) |" + '|'.join(f" {ms._VARSHNI[m]['beta']:.1f} " for m in MATS3) + "|")
    ms.set_gap_source('database')
    medb = {m: mt.electron_mass(M[m]) for m in MATS3}
    ms.set_gap_source('varshni', 0.0)      # leave the module as we found it, not on 300 K
    P("")
    P("**The electron mass settles this.** `m_e` is *derived* from the Kane expression rather than")
    P("tabulated (aestimo's database lists InAs `m_e = 0.4`, an order of magnitude off), so it is")
    P("a consistency check on `Eg`, `Ep`, `delta_so` and `F` together:")
    P("")
    P("| m_e (m0) | InAs | GaSb | InSb |")
    P("|---|---|---|---|")
    P("| derived with `database` gaps |" + '|'.join(f" {medb[m]:.5f} " for m in MATS3) + "|")
    P("| derived with 0 K Varshni gaps |" + '|'.join(f" {me0[m]:.5f} " for m in MATS3) + "|")
    P("| the review's own tabulated `m_e` |" +
      '|'.join(f" {M[m]['m_e']:.5f} " for m in MATS3) + "|")
    P("")
    P(f"With 0 K gaps the derived masses land on the tabulated values essentially exactly; with")
    P(f"the 300 K database gaps InSb comes out {medb['InSb']:.4f} against "
      f"{M['InSb']['m_e']:.4f}, a "
      f"{abs(medb['InSb']/M['InSb']['m_e']-1)*100:.0f}% error. `Ep` and `F` are 0 K quantities,")
    P("so **0 K is the self-consistent choice**. This is independent of the Pryor–Pistol")
    P("comparison and points the same way.")
    P("")
    P("---")
    P("")
    P("## Known problems, in priority order")
    P("")
    P("### 1. `a_gap` — RESOLVED. Three errors in the source database, now corrected")
    P("")
    P("The deformation potentials now come from `bandparameters_vurgaftman2001.xlsx`, read from")
    P("the review's own tables rather than from aestimo's copy of them. Three database errors:")
    P("")
    P("| | database | review | |")
    P("|---|---|---|---|")
    P("| `a_v` InAs | +1.00 | -1.00 | **sign flipped** |")
    P("| `a_v` InSb | +0.31 | -0.36 | **sign flipped** |")
    P("| `a_v` GaSb | -1.32 | -0.80 | right sign, wrong magnitude |")
    P("| `a_c` InSb | -6.04 | -6.94 | transposed digit? |")
    P("| `a_c` GaSb | -9.33 | -7.50 | |")
    P("| gaps | ~300 K | 0 K | see the mass check above |")
    P("")
    P("The review fixes the sign convention explicitly: *\"the change in energy")
    P("dEg = a(exx+eyy+eyy) must be positive [under compression]. This implies a negative value")
    P("for a = a_c + a_v. Note that our sign convention for a_v is different from many other")
    P("works found in the literature.\"* So `a_gap = a_c + a_v`, which this module already")
    P("assumed -- the database had simply flipped `a_v` for InAs and InSb. GaSb was the only")
    P("correct one, which is the opposite of what `GASB_AV_CONVENTION` was built to fix; that")
    P("switch is now deprecated.")
    P("")
    P("| a_gap | InAs | GaSb | InSb |")
    P("|---|---|---|---|")
    P("| database (old) | -4.08 | -8.01 | -5.73 |")
    P("| review (now in force) |" + '|'.join(
        f" **{mt.a_gap(M[m]):+.2f}** " for m in MATS3) + "|")
    p1998 = pr.PRYOR_TABLE_I['InAs']
    P(f"| Pryor 1998 Table I, InAs only | {p1998['a_c']+p1998['a_v']:+.2f} | | |")
    P("")
    P("`scripts/insb_pryor_pistol_check.py` back-derived -7.29 eV for InSb from Pryor & Pistol's")
    P("Table I well *before* the workbook was consulted; the review gives -7.30. That 10 meV")
    P("agreement is what identified the error as parametric rather than numerical, and with it")
    P("corrected the well now reproduces their Table I to **0 meV on both band edges**.")
    P("")
    P("### 2. What is still unverified")
    P("")
    P("| parameter | materials | note |")
    P("|---|---|---|")
    P("| `e14` | all four | piezoelectric. Present in the workbook, but as an **addition to the "
      "sheet** — the review's band-parameter tables do not cover piezoelectric constants. And "
      "the sign disagrees with Pryor 1998 (below). Still a knob. |")
    P("| `eps_R` | all four | static dielectric constant, likewise an addition to the sheet, and "
      "a 300 K value used at every temperature. Enters only the piezoelectric potential. |")
    P("")
    P("**The `e14` sign.** The workbook gives `e14` negative for all four binaries; "
      f"`pryor1998.PRYOR_TABLE_I`, transcribed from the arXiv preprint, gives the same "
      f"magnitudes positive (GaAs +0.159, InAs +0.045 against {M['GaAs']['e14']:+.3f} and "
      f"{M['InAs']['e14']:+.3f} here).")
    P("Zincblende has only one independent piezoelectric constant, so a global sign flip flips")
    P("the piezoelectric potential everywhere and swaps which side of the dot each carrier is")
    P("pushed toward. It does **not** change `|phi|`, the C4 antisymmetry, or anything computed")
    P("with `use_piezo=False`. `pryor1998` is a benchmark fixture reproducing a published figure")
    P("and keeps its own values, so the two deliberately disagree; if you compare a piezo result")
    P("here against a Pryor figure, check that sign first.")
    P("")
    _dvals = ', '.join('{} {:.1f}'.format(m, M[m]['d']) for m in MATS3)
    P(f"`d` is no longer among these -- the review gives it for all three ({_dvals} eV), which "
      "also corrected the GaSb and InSb guesses of -4.6 and -5.0. Likewise GaSb `C44`.")
    P("")
    P("`d` has exactly zero leverage on a biaxially strained well (no off-diagonal strain), so it")
    P("could not have contributed to the benchmark discrepancy. It does matter for dots.")
    P("")
    P("### 3. Other cross-check discrepancies against Pryor 1998 Table I (InAs only)")
    P("")
    P("| parameter | Pryor 1998 | materials_sb | diff |")
    P("|---|---|---|---|")
    p = pr.PRYOR_TABLE_I['InAs']
    for k in ('Eg', 'Ep', 'gamma1L', 'gamma2L', 'gamma3L', 'delta_so', 'b', 'd', 'a_c', 'a_v'):
        if k in p:
            d = M['InAs'][k] - p[k]
            flag = ' **check**' if abs(d) > 0.3 else ''
            P(f"| `{k}` | {p[k]:.3f} | {M['InAs'][k]:.3f} | {d:+.3f}{flag} |")
    P("")
    P("")
    P("`a_c` and `a_v` differ a lot individually while their SUM agrees to 80 meV "
      f"({p['a_c']+p['a_v']:+.2f} vs {M['InAs']['a_c']+M['InAs']['a_v']:+.2f}). That is exactly "
      "what the review warns about: *\"The distribution of the hydrostatic pressure shift")
    P("between the conduction and valence bands is generally based from theoretical predictions")
    P("in this review.\"* The split between bands is model-dependent; only `a_gap` is constrained")
    P("by experiment. So this row is agreement, not disagreement -- and it is why `a_gap` is the")
    P("quantity to check.")
    P("")
    P("`Ep` at -0.7 eV and the Luttingers do differ genuinely between the two sources. They feed")
    P("the derived mass and the eight-band Hamiltonian, so they are worth knowing about, but the")
    P("0 K derived masses reproduce the review's tabulated values exactly with the numbers in")
    P("force here.")
    P("")
    P("---")
    P("")
    P("## Status")
    P("")
    P("| item | state |")
    P("|---|---|")
    P("| `a_gap` for all three | **resolved** -- from the review; well benchmark passes to 0 meV |")
    P("| `a_v` sign convention | **resolved** -- review states `a_gap = a_c + a_v`, its `a_v` is "
      "negative; db had flipped InAs and InSb |")
    P("| InSb `a_c` | **resolved** -- -6.94, not the db's -6.04 |")
    P("| gap temperature | **resolved** -- 0 K, confirmed independently by the derived masses |")
    P("| `d`, GaSb `C44` | **resolved** -- in the review's tables after all |")
    P("| `VBO` | **resolved** -- InAs moved 10 meV; offsets now match the review exactly |")
    P("| lattice constant | **resolved** -- now temperature-dependent, consistent with the gaps |")
    P("| GaAs, and both alloys | **added** -- four binaries and In(x)Ga(1-x)Sb / InAs(1-x)Sb(x) |")
    P("| `e14`, `eps_R` | **still unverified** -- additions to the sheet, not in the review's "
      "band-parameter tables; `e14`'s sign disagrees with Pryor 1998. Knobs |")
    P("| alloy `m_e` | **inconsistent in the source** -- bowed table mass and Kane-derived mass "
      "differ by 9-16%; see the alloy section |")
    P("| `Ep`, Luttingers: Pryor 1998 vs Vurgaftman 2001 | source difference, not an error |")
    P("")
    P("Regenerate this sheet after any parameter change:")
    P("`python scripts/dump_sb_parameters.py > SB_PARAMETERS.md`")
